# Generated by Django 2.2.5 on 2019-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvRaw', models.CharField(max_length=1000000000)),
            ],
            options={
                'verbose_name_plural': 'resumes',
            },
        ),
    ]
